version: 0.2

phase:
  install:
    commands:
      - composer self-update --1
      - composer install -n --no-dev --prefer-dist
      - ngm cli

  build:
    commands:
      - npm run prod

artifacts:
  files:
    - './**/*'
